config/routes.rb
Rails.application.routes.draw do
devise_for :users
resources :signs
resources :feedbacks
get "about" => "signs#about", as: :about
get "contact" => "signs#contact", as: :contact
get "Today's Data" => "astrodatas#show", as: :todaysdata

root 'signs#index'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :user
end

app/models/sign.rb
class Sign < ActiveRecord::Base
	validates_presence_of :slug
	def to_param
		slug
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feedbacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/astrodatas_controller.rb
class AstrodatasController < ApplicationController
  #before_action :authenticate_user!, only: [:new, :create]

  def show
    # Date Information
      year = Time.now.year
      month = Time.now.month  
      day = Time.now.day
      hour = Time.now.hour
      tm = Date.today +1
      year_tm = tm.year
      month_tm = tm.month
      day_tm = tm.day
      hour_tm = 0

    # Geographic Location
      longitude = -73.985428
      latitidue = 40.748817
      altitude = 13


    # Get the Julian day number
    jd = Swe4r::swe_julday(year, month, day, hour)
    Swe4r::swe_set_topo(longitude, latitidue, altitude)

    jd_tm = Swe4r::swe_julday(year_tm, month_tm, day_tm, hour_tm)
    Swe4r::swe_set_topo(longitude, latitidue, altitude)

  # Set the sidereal mode for sidereal positions
    Swe4r::swe_set_sid_mode(Swe4r::SE_SIDM_LAHIRI, 0, 0)

    # Get the ayanamsha (the distance of the tropical vernal point from the sidereal zero point of the zodiac)
    ayanamsha = Swe4r::swe_get_ayanamsa_ut(jd)
    ayanamsha_tm = Swe4r::swe_get_ayanamsa_ut(jd_tm)
    # Get the longitude and latitude of various planets
    @sun_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_SUN, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @moon_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_MOON, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @mercury_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_MERCURY, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @venus_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_VENUS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @mars_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_MARS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @jupiter_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_JUPITER, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @saturn_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_SATURN, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @uranus_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_URANUS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @neptune_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_NEPTUNE, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @pluto_body = Swe4r::swe_calc_ut(jd, Swe4r::SE_PLUTO, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)

    @sun_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_SUN, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @moon_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_MOON, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @mercury_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_MERCURY, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @venus_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_VENUS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @mars_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_MARS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @jupiter_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_JUPITER, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @saturn_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_SATURN, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @uranus_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_URANUS, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @neptune_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_NEPTUNE, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)
    @pluto_body_tm = Swe4r::swe_calc_ut(jd_tm, Swe4r::SE_PLUTO, Swe4r::SEFLG_MOSEPH|Swe4r::SEFLG_SPEED|Swe4r::SEFLG_TOPOCTR|Swe4r::SEFLG_SIDEREAL)


      def calculate(l)
        if (l>0 ==true) & (l<30==true)
          return "Taurus"
        elsif (l>30 ==true) & (l<60==true)
          return "Gemini"
        elsif (l>60 ==true) & (l<90==true)
          return "Cancer"
        elsif (l>90 ==true) & (l<120==true)
          return "Leo"
        elsif (l>120 ==true) & (l<150==true)
          return "Virgo"
        elsif (l>150 ==true) & (l<180==true)
          return "Libra"
        elsif (l>180 ==true) & (l<210==true)
          return "Scorpio"
        elsif (l>210 ==true) & (l<240==true)
          return "Sagittarius"
        elsif (l>240 ==true) & (l<270==true)
          return "Capricorn"
        elsif (l>270 ==true) & (l<300==true)
          return "Aquarius"
        elsif (l>300 ==true) & (l<330==true)
          return "Pisces"
        elsif (l>330.00==true) & (l<360 ==true)
          return "Aries"
        else
          return "Error"
        end
      end
  @sun_position=calculate(@sun_body[0])
  @moon_position=calculate(@moon_body[0])
  @mercury_position=calculate(@mercury_body[0])
  @venus_position=calculate(@venus_body[0])
  @mars_position=calculate(@mars_body[0])
  @jupiter_position=calculate(@jupiter_body[0])
  @saturn_position=calculate(@saturn_body[0])
  @uranus_position=calculate(@uranus_body[0])
  @neptune_position=calculate(@neptune_body[0])
  @pluto_position=calculate(@pluto_body[0])

  @sun_position_tm=calculate(@sun_body_tm[0])
  @moon_position_tm=calculate(@moon_body_tm[0])
  @mercury_position_tm=calculate(@mercury_body_tm[0])
  @venus_position_tm=calculate(@venus_body_tm[0])
  @mars_position_tm=calculate(@mars_body_tm[0])
  @jupiter_position_tm=calculate(@jupiter_body_tm[0])
  @saturn_position_tm=calculate(@saturn_body_tm[0])
  @uranus_position_tm=calculate(@uranus_body_tm[0])
  @neptune_position_tm=calculate(@neptune_body_tm[0])
  @pluto_position_tm=calculate(@pluto_body_tm[0])
end

end
  

  #Calculate the sign of the Sun using longitude conditionals

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  #before_action :authenticate_user!, only: [:new, :create]
  def new
    @feedback= Feedback.new
  end

  def create
    safe_feedback = params.require(:feedback).permit(:helpful, :accurate, :interested, :comments)
    @feedback = current_user.feedbacks.new safe_feedback

    @feedback.save
    redirect_to @feedback
  end

  def show
    @feedback= Feedback.find params[:id]
  end

  def index
    @classifieds = Feedback.last(30)
  end
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  #before_action :authenticate_user!, only: [:new, :create, :destroy]
  #before_action :set_sign, only: [:show, :edit, :update, :destroy]
  def index
  	@signs = Sign.all
  end

  def about
  end

  def contact
  end

  def show
    begin
      @sign= Sign.find_by_slug(params[:id])
    
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json @sign}
      end

    rescue
      redirect_to root_path, notice: "Unavailable"
    end
  end


  # def new
  # 	@painting = Painting.new
  # end

  # def edit
  # end

  # def create
  # 	@painting =Painting.create(painting_params)

  # 	if @painting.save
  # 		redirect_to painting_path(@painting), notice: "New painting added."
  # 	else
  # 		render :new
  # 	end
  # end

  # def update
  # 	if @painting.update(painting_params)
  # 	redirect_to painting_path(@painting), notice: "Painting was updated"
  # 	else
  # 		render :edit
  # 	end
  # end

  # def destroy
  # 	@painting.destroy
  # 	redirect_to root_path
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/astrodatas/show.html.erb
<div class="view">
	<% if (@sun_position != @sun_position_tm)%>
	<p><%= "The Sun is in #{@sun_position} now and enters #{@sun_position_tm} today." %></p>
	<% else %>
	<p><%= "The Sun is in #{@sun_position}" %></p>
	<% end %>

	<% if (@moon_position != @moon_position_tm)%>
	<p><%= "The Moon is in #{@moon_position} now and enters #{@moon_position_tm} today." %></p>
	<% else %>
	<p><%= "The Moon is in #{@moon_position}" %></p>
	<% end %>

	<% if (@mercury_position != @mercury_position_tm)%>
	<p><%= "Mercury is in #{@mercury_position} now and enters #{@mercury_position_tm} today." %></p>
	<% else %>
	<p><%= "Mercury is in #{@mercury_position}" %></p>
	<% end %>

	<% if (@venus_position != @venus_position_tm)%>
	<p><%= "Venus is in #{@venus_position} now and enters #{@venus_position_tm} today." %></p>
	<% else %>
	<p><%= "Venus is in #{@venus_position}" %></p>
	<% end %>

	<% if (@mars_position != @mars_position_tm)%>
	<p><%= "Mars is in #{@mars_position} now and enters #{@mars_position_tm} today." %></p>
	<% else %>
	<p><%= "Mars is in #{@mars_position}" %></p>
	<% end %>
	
	<% if (@jupiter_position != @jupiter_position_tm)%>
	<p><%= "Jupiter is in #{@jupiter_position} now and enters #{@jupiter_position_tm} today." %></p>
	<% else %>
	<p><%= "Jupiter is in #{@jupiter_position}" %></p>
	<% end %>
	
	<% if (@saturn_position != @saturn_position_tm)%>
	<p><%= "Saturn is in #{@saturn_position} now and enters #{@saturn_position_tm} today." %></p>
	<% else %>
	<p><%= "Saturn is in #{@saturn_position}" %></p>
	<% end %>
	
	<% if (@uranus_position != @uranus_position_tm)%>
	<p><%= "Uranus is in #{@uranus_position} now and enters #{@uranus_position_tm} today." %></p>
	<% else %>
	<p><%= "Uranus is in #{@uranus_position}" %></p>
	<% end %>

	<% if (@neptune_position != @neptune_position_tm)%>
	<p><%= "Neptune is in #{@neptune_position} now and enters #{@neputne_position_tm} today." %></p>
	<% else %>
	<p><%= "Neptune is in #{@neptune_position}" %></p>
	<% end %>

	
	<% if (@pluto_position != @pluto_position_tm)%>
	<p><%= "Pluto is in #{@pluto_position} now and enters #{@pluto_position_tm} today." %></p>
	<% else %>
	<p><%= "Pluto is in #{@pluto_position}" %></p>
	<% end %>

</div>

app/views/feedbacks/_form.html.erb
<%= form_for @feedback do |f| %>
	<% if @feedback.errors.any? %>
		<div class="errors">
			<%= @feedback.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>	
		</div>
		<% end %>
	<% end %>
<div class="view">
	<h3>Leave Feedback</h3>
<div class="form-group">
	<p>Was this horoscope helpful to you?</p>
	<p><%= radio_button_tag(:helpful, "helpful") %> 
	<%= f.label "helpful"%>
	<%= radio_button_tag(:helpful, "not helpful") %>
	<%= f.label "not helpful" %>
	<%= radio_button_tag(:helpful, "neither helpful nor not helpful") %>
	<%= f.label "neither helpful nor not helpful" %></p>
</div>

<div class="form-group">
	<p>Was this horoscope accuarate for you?</p>
	<p><%= radio_button_tag(:accurate, 1) %>
	<%= f.label "not accurate"%> 
	<%= radio_button_tag(:accurate, 2) %>
	<%= f.label "minimally accurate"%> 
	<%= radio_button_tag(:accurate, 3) %>
	<%= f.label "moderately accurate"%> 
	<%= radio_button_tag(:accurate, 4) %>
	<%= f.label "mostly accurate"%> 
	<%= radio_button_tag(:accurate, 5) %>
	<%= f.label "extremely accurate"%> 
	 </p>
</div>

<div class="form-group">
	<p>What areas are you most interested in seeing your horoscope?</p>
	<p><%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Career")%>
	<%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Romantic")%>
	<%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Spiritual")%>
	<%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Social")%>
	<%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Financial")%>
	<%= check_box_tag(:interested) %>
	<%= label_tag(:interested, "Health")%>
	</p>
</div>

<div class="form-group">
<%= f.label "comments" %>
<p><%= f.text_area :comments, placeholder: "enter comment" %></p>
</div>

<div class-"form-group">
<%= f.submit "leave feedback" %>

</div>
</div>
<% end %>

app/views/feedbacks/new.html.erb
<%= render 'form' %>

app/views/feedbacks/show.html.erb
<h1>Thank you for your Feedback!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Astro-Logical"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous"> 

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script> 
</head>
<body>
	<%= render 'shared/navbar' %>

<main>
	
		<div class="container-fluid">
		<div class="row">
<!-- 			<div class="span12"></div>
			<div class="text-muted"><p class="notice"><%= notice %></p></div>
			<p class="alert"><%= alert %></p> -->
			<%= yield %>
		</div>
	</div>

</main>
</body>
</html>

app/views/shared/_navbar.html.erb
<header role="banner">
  <img id="logo-main" src="<%=asset_path('logo.png') %>" width="200" alt="Astro-Logical">
<!-- <nav id="navbar-primary" class="navbar navbar-default" role="navigation"> -->
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
  
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-primary-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-primary-collapse">
      <ul class="nav navbar-nav">
        <li class="active"> 
        <% if user_signed_in? %>
        <li><%= link_to 'sign out', destroy_user_session_path, method: :delete %>  </li>
        <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %> </li>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %> </li>
        <li><%= link_to "Home", root_path %></li>
       <li> <%= link_to "About", about_path %></li>
       <li> <%= link_to "Today's Data", todaysdata_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>
</header><!-- header role="banner" -->

app/views/signs/_form.html.erb
	<h3>Leave Feedback</h3>
<%= form_for @feedback do |f| %>
	<% if @feedback.errors.any? %>
		<div class="errors">
			<%= @feedback.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>	
		</div>
	<% end %>

	<p>
		<h3>Leave Feedback</h3>
	</p>

	<p>
		<%= f.radio_button_tag(:helpful, "Was this horoscope helpful to you?") %>
		<%= f.label_tag(:helpful, "Helpful") %>
		<%= f.label_tag(:helful, "Not Helpful") %>
	</p>
		</div>
	<% end %>

<% end %>

app/views/signs/about.html.erb
<h1>About This App</h1>

app/views/signs/index.html.erb
<h1></h1>
<% if user_signed_in? %>
	<div><span>Hello <%= current_user.email %> </span>
<% else %>
<% end %>
<% @signs.each do |sign| %>
	     		<div class="col-mod-2">
				     <!-- <div class="sign_image">  -->
			        	<p><%= link_to "hiii #{image_tag(asset_path('pisces_1.png'))}", sign_path(sign) %></p>
			       	<!--  </div>	 -->
			    </div>
		
 <% end %>

app/views/signs/show.html.erb
<div class="view">
	<div class="row">
		<div class='col-md-6"'>
			<div class="sign_image_2"><%= image_tag @sign.image_2 %></div>
			<p> <%= @sign.birth_range %></p>
			<p> Horoscope for <%= Time.now.strftime("%m/%d/%Y") %></p>
			<p> <%= IO.binread(@sign.horoscope) %></p>
			<p><%= link_to "Leave Feedback", new_feedback_path(@feedback) %></p>
		</div>
	</div>
</div>